homepage:
  method: get
  path: /
  controller: \MFFC\Controllers\HomeController@home
about:
  method: get
  path: /about
  controller: \MFFC\Controllers\HomeController@about
contact:
  method: get
  path: /contact
  controller: \MFFC\Controllers\HomeController@contact
portfolio:
  method: get
  path: /portfolio
  controller: \MFFC\Controllers\HomeController@portfolio
services:
  method: get
  path: /services
  controller: \MFFC\Controllers\HomeController@services